name: Build Docker images

on:
  push:
    branches: [ master ]
    paths:
    - '**Dockerfile**'

  pull_request:
    branches: [ master ]
    paths:
    - '**Dockerfile**'

jobs:

  build:
    name: Build image '${{ matrix.version }}'

    strategy:
      fail-fast: false
      matrix:
        version:
          - 18.04
          - 20.04
          - 22.04

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Build Docker container '${{ matrix.version }}'
      uses: docker/build-push-action@v2
      with:
        tags: |
          ossystems/yocto-env:${{ matrix.version }}
          ossystems/yocto-env:${{ matrix.version }}
        build-args: version=${{ matrix.version }}
        push: false
