name: Publish the Docker images

on:
  push:
    tags:
      - v*

jobs:

  build:
    name: Build and publish image '${{ matrix.version }}' to Docker Registry

    strategy:
      fail-fast: false
      matrix:
        version:
          - 14.04
          - 16.04
          - 18.04
          - 20.04

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - uses: docker/setup-buildx-action@v1

    - name: Get release version
      id: get_version
      run: echo RELEASE_VERSION=${GITHUB_REF:10} >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker container '${{ matrix.version }}'
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
          ossystems/yocto-env:${{ matrix.version }}
          ossystems/yocto-env:${{ matrix.version }}-${{ env.RELEASE_VERSION }}
        build-args: version=${{ matrix.version }}
        push: true
